
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ALPINE_MIRROR=${ALPINE_MIRROR:-}
        - NPM_REGISTRY_MIRROR=${NPM_REGISTRY_MIRROR:-}
        - PNPM_REGISTRY_MIRROR=${PNPM_REGISTRY_MIRROR:-}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
